config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  root 'questions#index'

  post 'questions/:id/voteup' => 'questions#voteup', as: 'vote_question'
   post 'questions/:id/delete_vote' => 'questions#delete_vote', as: 'delete_vote'

  post 'answers/:id/voteup' => 'answers#voteup', as: 'vote_answer'
  post 'answers/:id/delete_vote' => 'answers#delete', as: 'delete_vote_answer'

  resources :users
  resources :questions do
      resources :comments
  end
  resources :answers do
    resources :comments
  end

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#  user_id     :integer
#

class Question < ActiveRecord::Base

	belongs_to :user
	has_many :answers, dependent: :destroy
	has_many :comments, as: :commenter, dependent: :destroy
	has_many :votes, as: :votable, dependent: :destroy
	validates :title, :description, presence: true

	def self.search(query)
		where("title like ? OR description like ?", "%#{query}%", "%#{query}%")
	end
end

app/controllers/questions_controller.rb
	class QuestionsController < ApplicationController

		def index
			if params[:search]
				@questions= Question.search(params[:search]).order("created_at DESC")
			else
				@questions = Question.order("created_at DESC")
			end	
		end

		def show
			@question= Question.find(params[:id])
			@answer=Answer.new			
		end

		def new
			@question=Question.new
		end


		def create
			@question= Question.new(question_params)
			@question.user = current_user
			if @question.save 
				flash[:success]= 'La pregunta ha sido creada con exitó'
				redirect_to @question
			else
				render :new
			end 
		end

		def edit
			@question=Question.find(params[:id])
		end

		def update
			@question=Question.find(params[:id])
			if @question.update(question_params)
				redirect_to questions_path, notice:'La pregunta fue editada con exito'
			else	
				render 'edit'			
			end	
		end

		def destroy
			Question.find(params[:id]).destroy
			redirect_to questions_path, notice: 'La pregunta fue eliminada con exitó'
		end

		def voteup
			question=Question.find(params[:id])
			question.votes.create(user: current_user)
			redirect_to question_path
		end

		def delete_vote
			question=Question.find(params[:id])
			question.votes.where(user:current_user).take.try(:destroy)
			redirect_to question_path
		end

		def search
		end

		private

		def question_params
			params.require(:question).permit(:title, :description)
		end
	end

app/helpers/questions_helper.rb
module QuestionsHelper



			

end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
	<%= render 'shared/error_messages', object: @question %>
	<div class="form-group">
		<%= f.text_field :title, class: "form-control", placeholder: "Ingresa el titulo de la pregunta"  %>
	</div>
	<div class="form-group">
		<%= f.text_area :description, class: "form-control", placeholder: "Ingresa la desripción"  %>
		<%= f.hidden_field :votes, value: 0 %>
	</div>

	<div class="form-group">
		<%= f.submit 'Crear pregunta', class: "btn btn-primary btn-lg btn-block" %>
	</div>
<% end %>

app/views/questions/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">

			<h1>Editar pregunta</h1>
			
			<%= render 'form' %>


		</div>
	</div>
</div>

app/views/questions/index.html.erb
<div class="container">
	<div class="text-right">
		<% if logged_in?%>
		<%= link_to "<span class='glyphicon glyphicon-plus'></span> Nueva pregunta".html_safe, new_question_path, class: "btn btn-primary" %>
		<% end %>
	</div>
	<div class="row">
		<% @questions.each do |q| %>
		<div class="col-md-12 question">
			<div class="col-md-1 text-center">
				<h3><%= q.votes.count %></h3>
				<p>Votos</p>
			</div>
			<div class="col-md-1 text-center">
				<h3><%= q.answers.count %></h3>
				<p>Respuestas</p>
			</div>

			<div class="col-md-10">
				<h3><%= link_to q.title, question_path(q) %></h3>
				<%=  q.user.email if q.user %>
				<p><%= q.updated_at.strftime("%Y-%m-%d") %></p>
			</div>
		</div>
		<% end %>

	</div>
</div>

app/views/questions/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">

			<h1>Nueva pregunta</h1>
			
			<%= render 'form' %>


		</div>
	</div>
</div>

app/views/questions/show.html.erb
<div class="container-fluid">
	<div class="row">



		<!-- show question -->
		<div class="col-md-10 col-md-offset-1">
			<h1><%=@question.title  %></h1>
		</div>

		<div class="col-md-10 col-md-offset-1">
			<div class="row">
				<!-- show votes question-->
				<div class="col-md-1">
					<% if @question.votes.exists?(user: current_user) %>
					<%= link_to delete_vote_path(@question.id), method:'post' do %>
					<h2 class="glyphicon glyphicon-triangle-top" style="margin-left:20px; color:#A9A9A9"></h2>
					<% end %>
					<% else %>

					<%= link_to vote_question_path(@question.id), method: 'post' do %>
					<h2 class="glyphicon glyphicon-triangle-top" style="margin-left:20px"></h2>
					<% end %>
					<% end %>
					<h2 class= 'text-center' style="margin-top:-10px; margin-left:10px"><%= @question.votes.count %><h2>
				</div>
					<!-- show descryption question-->
				<div class="col-md-11">
						<p><%= markdown(@question.description) %></p>
				</div>

				<!-- show comments question  -->
				<div class="question-comments col-md-11 col-md-offset-1">
					<%  @question.comments.each do |comment| %>
					<div class="comment">
						<%= markdown(comment.body)%>
					</div>
					<% end %>
				</div>
				<% if logged_in? %>
				<!-- do a comment question -->
				<div class="col-md-11 col-md-offset-1">
					<%= form_for ([@question, @question.comments.build]) do |f| %>
					<%= f.text_area :body, class: "form-control", placeholder: "Ingresa un comentario" %>
					<%= f.hidden_field :commenter_type, :value =>'Question' %>
					<%= f.hidden_field :commenter_id, :value => @question.id %>
					<%= f.submit "Crear comentario", class: "btn btn-primary pull-right btn-sm" %>
					<%  end %>
				</div>
				<% end %>
			</div>
		</div>


		<div class="row">

			<div class="col-md-10 col-md-offset-1">
				<h2>(<%= @question.answers.count %>) Respuesta(s)</h2>
			</div>
			<!-- list answers  -->
			<div class="col-md-10 col-md-offset-1">
				<% @question.answers.where.not(id:nil).each do |answer| %>
				<div class="row answer" id="answer_<%= answer.id %>">
					<!-- show votes answer -->
					<div class="col-md-1">

						<% if answer.votes.exists?(user:current_user) %>

						<%= link_to delete_vote_answer_path(answer.id), method: 'post' do %>
						<h2 class="glyphicon glyphicon-triangle-top" style="margin-left:20px; color:#A9A9A9"></h2>
						<% end %>


						<% else %>

						<%= link_to vote_answer_path(answer.id), method: 'post' do %>
						<h2 class="glyphicon glyphicon-triangle-top" style="margin-left:20px"></h2>
						<% end %>

						<% end %>



						<h2 class= 'text-center' style="margin-top:-10px; margin-left:10px"><%= answer.votes.count %></h2>
					</div>
					<!-- answer body  -->
					<div class="col-md-11">
						<p><%= markdown(answer.body)%></p>
					</div>

					<div class="col-md-11 ccol-md-offset-1">
						<!-- list answer comments  -->
						<% answer.comments.each do |comment| %>
						<div class="comment">
							<%= markdown(comment.body) %>
						</div>
						<% end %>
					</div>
					<% if logged_in? %>
					<div class="col-md-11 col-md-offset-1">
						<!-- do an answer comment  -->
						<%= form_for ([answer, answer.comments.build]) do |f| %>
						<%= f.text_area :body, class: "form-control", placeholder: "Ingresa un comentario" %>
						<%= f.hidden_field :commenter_type, :value => 'Answer' %>
						<%= f.hidden_field :commenter_id, value: answer.id %>
						<%= f.submit "Crear comentario", class: "btn btn-primary pull-right btn-sm submit-botton" %>
						<%  end %>
					</div>
					<% end %>
				</div>
				<% end %>
			</div>


			<% if logged_in? %>
			<div class="col-md-10 col-md-offset-1">
				<h2>Tu respuesta</h2>
				<%= form_for @answer do |f| %>
				<%= render 'shared/error_messages', object: @answer %>
				<%= f.text_area :body, class: "form-control", placeholder: "Ingresa tu respuesta" %>
				<%= f.hidden_field :question_id, :value => @question.id %>
				<%= f.hidden_field :user_id, :value => current_user.id %>
				<%= f.submit "Crear respuesta",class: "btn btn-primary" %>
				<%  end %>
			</div>

			<% end %>

		</div>
	</div>